---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: newrelic
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/metrics"
      - "nodes/stats"
      - "nodes/proxy"
      - "pods"
      - "services"
      - "namespaces"
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: newrelic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic
subjects:
  - kind: ServiceAccount
    name: newrelic
    namespace: default
---